### ISSUE TITLE
NameError: name 'reload' is not defined

### ISSUE THREAD

**Issue by weigeloveu** [cary-zhou/1024_dagaier_spider#1]
大佬这个错误是咋回事啊啊

PS C:\Users\x\Downloads\1024_dagaier_spider> python .\达盖尔.py

Traceback (most recent call last):
  File ".\达盖尔.py", line 6, in <module>
    reload(sys)
NameError: name 'reload' is not defined
PS C:\Users\x\Downloads\1024_dagaier_spider>

**Comment by weigeloveu** [comment]
看了一下脚本是python 2.7的，换成2.7之后运行出现如下错误。因为是本地的端口是1080，所以自己把1088改成了1080，是这个原因吗？
  File ".\达盖尔.py", line 177, in <module>
    Page_Obj=requests.get(PageList,headers=header,proxies=proxy,timeout=10)
  File "C:\Python27\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPConnectionPool(host='t66y.com', port=80): Max retries exceeded with url: /thread0806.php?fid=16&search=&page=1 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x0000000003B0D848>: Failed to establish a new connection: [Errno 10061] ',))

**Comment by cary-zhou** [comment]
错误表示不能建立与SOCKS服务器的连接(SS or SSR)。可能是由于你的梯子监听的不是127.0.0.1，而程序使用的是127.0.0.1造成的，把127.0.0.1换成本地连接的IP地址试试。

**Comment by AngusLkc** [comment]
错误表示程序不能建立到socks5服务器的连接(ss or ssr)，可能是由于梯子没有监听127.0.0.1而程序连接的是127.0.0.1导致的，程序里127.0.0.1换成你电脑本地连接的IP地址试试。
最新的commit已经不含"reload(sys)"代码，现在我已测试python2.7和python3.7均能正常运行。请下载最新的代码再试试。
